#!/usr/bin/env bash

fail() {
    MESSAGE=$1
    RED='\033[0;31m'
    NC='\033[0m'
    echo -e "$RED Failure: $MESSAGE $NC"
    exit 1;
}

continue() {
    result=$1
    MESSAGE=$2
    if [ $result -ne 0 ]; then
        fail $MESSAGE
    fi
}

Usage() {
    echo ""
    echo "Usage: ./zzz (test|build|install|publish)"
    echo ""
    echo "  This script will run the given gradle commands over the whole cross-compiled space of this project."
    echo ""
    echo "Example: ./zzz test"
    echo "  The above will run tests on the following branches, while attempting to merge master into each"
    echo "      master"
    echo "      master-kafka_0.10"
    echo ""
    fail "Missing at least one gradle command argument"
}


case "$1" in
    test)
        C="test --quiet"
        ALL="true"
        ;;
    build)
        C="build --quiet --exclude-task test --quiet"
        ALL="false"
        ;;
    install)
        C="install"
        ALL="false"
        ;;
    publish)
        C="uploadArchives -Pmaven-central --quiet"
        ALL="false"
        ;;
    *)
        Usage
        ;;
esac

MASTER="master"
continue $? "initializze"

#excute on master branch / all modules
git checkout $MASTER
continue $? "$MASTER: checkout"
MESSAGE="$MASTER: $C (all modules)"
echo $MESSAGE
./gradlew $C
continue $? $MESSAGE

#excute on kafka_0.10 / kafka modules only
BRANCH="master-kafka_0.10"
MESSAGE="$BRANCH: checkout"
echo $MESSAGE
git checkout $BRANCH
continue $? $MESSAGE
MESSAGE="$BRANCH: merge $MASTER"
echo $MESSAGE
git merge $MASTER
continue $? $MESSAGE
if [ $ALL == "true" ]; then
    MESSAGE="$BRANCH: $C"
    echo $MESSAGE
    ./gradlew $C
else
    MESSAGE="$BRANCH: $C (kafka modules)"
    echo $MESSAGE
    ./gradlew :kafka:avro-formatter-kafka:$C
    ./gradlew :kafka:avro-serde-kafka:$C
    ./gradlew :kafka:storage-kafka:$C
    ./gradlew :kafka:test-util-kafka:$C
fi
continue $? "$BRANCH: $C"


git checkout $MASTER
continue $? "Checkout back to root branch"
